name: CI

on:
  schedule:
    - cron: 0 */2 * * *
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     
      - uses: actions/checkout@v2
      
      - name: wget
        run: wget "$LINKS"
      
      - name: Run
        run: bash start.sh
      
        shell: bash
        env:
          LINKS: ${{secrets.LINK}}
          LINK2: ${{secrets.LINK2}}
