name: FirstStep

on:
  schedule:
    - cron: 0 */2 * * *
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     
      - uses: actions/checkout@v2
      
      - name: Run
        run: bash start.sh
        
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        env:
          LINK: ${{secrets.LINK}}
          LINK2: ${{secrets.LINK2}}
          LINK3: ${{secrets.LINK3}}
          shell: bash

